name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Navigate to the Testing directory
      - name: Navigate to Testing Directory
        working-directory: Testing
        run: pwd

      # Step 4: Start the backend service
      - name: Start Backend Service
        working-directory: Testing
        run: |
          nohup java -jar lib/demo-0.0.1-SNAPSHOT.jar &

      # Step 5: Wait for the backend service to start
      - name: Wait for Backend
        working-directory: Testing
        run: |
          for i in {1..10}; do
            nc -zv localhost 7081 && echo "Backend is up!" && break
            echo "Waiting for backend..."
            sleep 5
          done

      # Step 6: Run Serenity BDD API Tests
      - name: Run Serenity API Tests
        working-directory: Testing
        run: |
          mkdir -p target/site/serenity
<<<<<<<< HEAD:.github/workflows/run-tests.yml
          mvn clean verify
      
========
          mvn clean verify -Dtest="ApiTestRunner" -Dserenity.outputDirectory=target/site/serenity
>>>>>>>> 43d4c73e9fd4ea2fd3fcea6a4424fc82b4e3f574:.github/workflows/main.yml

      # Step 7: Save Serenity BDD Results as Artifacts
      - name: Archive Serenity API Results
        if: always()
        working-directory: Testing
        uses: actions/upload-artifact@v3
        with:
          name: serenity-results-api
          path: target/site/serenity

  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Navigate to the Testing directory
      - name: Navigate to Testing Directory
        working-directory: Testing
        run: pwd

      # Step 4: Install Chrome and WebDriver
      - name: Install Chrome
        working-directory: Testing
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      # Step 5: Run Serenity BDD UI Tests
      - name: Run Serenity UI Tests
        working-directory: Testing
        run: |
          mkdir -p target/site/serenity
          mvn clean verify -Dtest="UITest"

      # Step 6: Save Serenity BDD Results as Artifacts
      - name: Archive Serenity UI Results
        if: always()
        working-directory: Testing
        uses: actions/upload-artifact@v3
        with:
          name: serenity-results-ui
          path: target/site/serenity